### ISSUE TITLE
Anniversary Number being incorrect

### ISSUE THREAD

**Issue by ZeitHeld** [Friends-of-Monika/mas-presence#29] opened 2023-04-19 17:53 UTC
I just have my 2 year anniversary right now, and the Discord Presence says "3 years" however.

**Comment by dreamscached** [comment] 2023-04-19 17:56
Can you share your `db.mcal` file from the persistent files location? As it contains in-game calendar data and it may be sensitive (e.g. event names and dates, such as full birthdate, etc.), you can send it to me in a Discord DM on our server or share it here, if you prefer.

In addition to that, what does your in-game calendar say for the current date?

**Comment by ZeitHeld** [comment] 2023-04-19 19:03
Calendar says currently 19th April 2023, on a Wednesday. Date is marked with "2 years".
[db.zip](https://github.com/Friends-of-Monika/mas-presence/files/11276686/db.zip)

**Comment by dreamscached** [comment] 2023-04-19 19:15
I managed to reproduce the bug and determine the cause of it, thank you for your report. I'll look into it and release a fix when I'll get it fixed.

**Comment by dreamscached** [comment] 2023-04-30 14:14
Fixed in 300c425, will release an update shortly.

**Closed as completed by dreamscached** 2023-04-30 14:14 UTC
Labels: bug
